general.import = [ "~/.config/alacritty/moonfly.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 10

[window]
padding.x = 14
padding.y = 14
decorations = "None"
